INSERT INTO PRODUCT(PRODUCTNAME,PRICE)VALUES('SMARTPHONE',599.99),
INSERT INTO PRODUCT(PRODUCTNAME,PRICE)VALUES('LAPTOP',1299.99),
INSERT INTO PRODUCT(PRODUCTNAME,PRICE)VALUES('GAMING CONSOLE',399.99);



INSERT INTO REVIEW(REVIEWCONTENT,RATING,PRODUCTID)VALUES('GREAT BATTERY LIFE!',5,1),
INSERT INTO REVIEW(REVIEWCONTENT,RATING,PRODUCTID)VALUES('LAGS SOMETIMES.',3,1),
INSERT INTO REVIEW(REVIEWCONTENT,RATING,PRODUCTID)VALUES('PERFECT FOR MY DAILY TASKS!',4,2),
INSERT INTO REVIEW(REVIEWCONTENT,RATING,PRODUCTID)VALUES('BIT PRICEY,BUT WORTH IT.',4,2 ),
INSERT INTO REVIEW(REVIEWCONTENT,RATING,PRODUCTID)VALUES('AWESOME GAMING EXPERIENCE!',5,3),
INSERT INTO REVIEW(REVIEWCONTENT,RATING,PRODUCTID)VALUES('NEEDS MORE EXCLUSIVE GAMES',4,3);